/// <reference path="../pb_data/types.d.ts" />

// MCP Assistant (docs/mcp-assistant-design/MCP-ASSISTANT.md): the owner/staff-facing in-app chat
// assistant. Deliberately separate tables from `conversations`/`messages` (the WhatsApp customer
// channel) — two independent agents by construction, see the design doc §2. Every table is
// scoped to the staff member who owns the conversation, both here (defense in depth) and again
// in the server functions (`requireSession()` + an explicit `staff.id` check, same pattern as
// `src/features/leads/server/leads.ts`).
migrate(
  (app) => {
    const mcpConversations = new Collection({
      id: 'pbc_1000000300',
      name: 'mcp_conversations',
      type: 'base',
      system: false,
      listRule: "@request.auth.id != '' && staff = @request.auth.id",
      viewRule: "@request.auth.id != '' && staff = @request.auth.id",
      createRule: "@request.auth.id != ''",
      updateRule: "@request.auth.id != '' && staff = @request.auth.id",
      deleteRule: "@request.auth.id != '' && staff = @request.auth.id",
      fields: [
        {
          autogeneratePattern: '[a-z0-9]{15}',
          hidden: false,
          id: 'text3208210256',
          max: 15,
          min: 15,
          name: 'id',
          pattern: '^[a-z0-9]+$',
          presentable: false,
          primaryKey: true,
          required: true,
          system: true,
          type: 'text',
        },
        {
          cascadeDelete: true,
          collectionId: 'pbc_829252413', // staff
          hidden: false,
          id: 'relation_staff_1',
          maxSelect: 1,
          minSelect: 1,
          name: 'staff',
          presentable: false,
          required: true,
          system: false,
          type: 'relation',
        },
        {
          autogeneratePattern: '',
          hidden: false,
          id: 'text_title_1',
          max: 200,
          min: 0,
          name: 'title',
          pattern: '',
          presentable: true,
          primaryKey: false,
          required: false,
          system: false,
          type: 'text',
        },
        {
          hidden: false,
          id: 'select_channel_1',
          maxSelect: 1,
          name: 'channel',
          presentable: false,
          required: true,
          system: false,
          type: 'select',
          values: ['web', 'whatsapp'],
        },
        {
          hidden: false,
          id: 'date_last_message_at_1',
          max: '',
          min: '',
          name: 'last_message_at',
          presentable: false,
          required: false,
          system: false,
          type: 'date',
        },
        {
          hidden: false,
          id: 'autodate_created_1',
          name: 'created',
          onCreate: true,
          onUpdate: false,
          presentable: false,
          system: false,
          type: 'autodate',
        },
        {
          hidden: false,
          id: 'autodate_updated_1',
          name: 'updated',
          onCreate: true,
          onUpdate: true,
          presentable: false,
          system: false,
          type: 'autodate',
        },
      ],
    })
    app.save(mcpConversations)

    const mcpMessages = new Collection({
      id: 'pbc_1000000301',
      name: 'mcp_messages',
      type: 'base',
      system: false,
      listRule: "@request.auth.id != '' && conversation.staff = @request.auth.id",
      viewRule: "@request.auth.id != '' && conversation.staff = @request.auth.id",
      createRule: "@request.auth.id != '' && conversation.staff = @request.auth.id",
      updateRule: "@request.auth.id != '' && conversation.staff = @request.auth.id",
      deleteRule: "@request.auth.id != '' && conversation.staff = @request.auth.id",
      fields: [
        {
          autogeneratePattern: '[a-z0-9]{15}',
          hidden: false,
          id: 'text3208210256',
          max: 15,
          min: 15,
          name: 'id',
          pattern: '^[a-z0-9]+$',
          presentable: false,
          primaryKey: true,
          required: true,
          system: true,
          type: 'text',
        },
        {
          cascadeDelete: true,
          collectionId: 'pbc_1000000300', // mcp_conversations
          hidden: false,
          id: 'relation_conversation_1',
          maxSelect: 1,
          minSelect: 1,
          name: 'conversation',
          presentable: false,
          required: true,
          system: false,
          type: 'relation',
        },
        {
          hidden: false,
          id: 'select_role_1',
          maxSelect: 1,
          name: 'role',
          presentable: false,
          required: true,
          system: false,
          type: 'select',
          values: ['owner', 'assistant'],
        },
        {
          autogeneratePattern: '',
          hidden: false,
          id: 'text_body_1',
          max: 8000,
          min: 0,
          name: 'body',
          pattern: '',
          presentable: false,
          primaryKey: false,
          required: false,
          system: false,
          type: 'text',
        },
        {
          hidden: false,
          id: 'json_tool_calls_1',
          maxSize: 20000,
          name: 'tool_calls',
          presentable: false,
          required: false,
          system: false,
          type: 'json',
        },
        {
          hidden: false,
          id: 'autodate_created_2',
          name: 'created',
          onCreate: true,
          onUpdate: false,
          presentable: false,
          system: false,
          type: 'autodate',
        },
      ],
    })
    app.save(mcpMessages)

    const mcpActions = new Collection({
      id: 'pbc_1000000302',
      name: 'mcp_actions',
      type: 'base',
      system: false,
      listRule: "@request.auth.id != '' && conversation.staff = @request.auth.id",
      viewRule: "@request.auth.id != '' && conversation.staff = @request.auth.id",
      createRule: "@request.auth.id != '' && conversation.staff = @request.auth.id",
      updateRule: "@request.auth.id != '' && conversation.staff = @request.auth.id",
      deleteRule: "@request.auth.id != '' && conversation.staff = @request.auth.id",
      fields: [
        {
          autogeneratePattern: '[a-z0-9]{15}',
          hidden: false,
          id: 'text3208210256',
          max: 15,
          min: 15,
          name: 'id',
          pattern: '^[a-z0-9]+$',
          presentable: false,
          primaryKey: true,
          required: true,
          system: true,
          type: 'text',
        },
        {
          cascadeDelete: true,
          collectionId: 'pbc_1000000300', // mcp_conversations
          hidden: false,
          id: 'relation_conversation_2',
          maxSelect: 1,
          minSelect: 1,
          name: 'conversation',
          presentable: false,
          required: true,
          system: false,
          type: 'relation',
        },
        {
          cascadeDelete: true,
          collectionId: 'pbc_1000000301', // mcp_messages
          hidden: false,
          id: 'relation_message_1',
          maxSelect: 1,
          minSelect: 1,
          name: 'message',
          presentable: false,
          required: true,
          system: false,
          type: 'relation',
        },
        {
          autogeneratePattern: '',
          hidden: false,
          id: 'text_tool_name_1',
          max: 100,
          min: 0,
          name: 'tool_name',
          pattern: '',
          presentable: true,
          primaryKey: false,
          required: true,
          system: false,
          type: 'text',
        },
        {
          hidden: false,
          id: 'json_args_1',
          maxSize: 20000,
          name: 'args',
          presentable: false,
          required: false,
          system: false,
          type: 'json',
        },
        {
          hidden: false,
          id: 'select_status_1',
          maxSelect: 1,
          name: 'status',
          presentable: true,
          required: true,
          system: false,
          type: 'select',
          values: ['pending', 'editing', 'executing', 'done', 'cancelled'],
        },
        {
          hidden: false,
          id: 'json_diff_1',
          maxSize: 20000,
          name: 'diff',
          presentable: false,
          required: false,
          system: false,
          type: 'json',
        },
        {
          hidden: false,
          id: 'date_executed_at_1',
          max: '',
          min: '',
          name: 'executed_at',
          presentable: false,
          required: false,
          system: false,
          type: 'date',
        },
        {
          hidden: false,
          id: 'date_undo_expires_at_1',
          max: '',
          min: '',
          name: 'undo_expires_at',
          presentable: false,
          required: false,
          system: false,
          type: 'date',
        },
        {
          hidden: false,
          id: 'autodate_created_3',
          name: 'created',
          onCreate: true,
          onUpdate: false,
          presentable: false,
          system: false,
          type: 'autodate',
        },
        {
          hidden: false,
          id: 'autodate_updated_2',
          name: 'updated',
          onCreate: true,
          onUpdate: true,
          presentable: false,
          system: false,
          type: 'autodate',
        },
      ],
    })
    return app.save(mcpActions)
  },
  (app) => {
    const mcpActions = app.findCollectionByNameOrId('pbc_1000000302')
    app.delete(mcpActions)
    const mcpMessages = app.findCollectionByNameOrId('pbc_1000000301')
    app.delete(mcpMessages)
    const mcpConversations = app.findCollectionByNameOrId('pbc_1000000300')
    return app.delete(mcpConversations)
  },
)
