/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthRouteRouteImport } from './routes/auth/route'
import { Route as DashboardRouteRouteImport } from './routes/dashboard/route'
import { Route as OnboardingRouteRouteImport } from './routes/onboarding/route'
import { Route as ApiPingRouteImport } from './routes/api/ping'
import { Route as ApiWhatsappWebhookRouteImport } from './routes/api/whatsapp-webhook'
import { Route as AuthLoginRouteImport } from './routes/auth/login'
import { Route as AuthSetupRouteImport } from './routes/auth/setup'
import { Route as DashboardIndexRouteImport } from './routes/dashboard/index'
import { Route as DashboardCalendarRouteImport } from './routes/dashboard/calendar'
import { Route as DashboardConversationsRouteImport } from './routes/dashboard/conversations'
import { Route as DashboardCustomersRouteImport } from './routes/dashboard/customers'
import { Route as DashboardLeadsRouteImport } from './routes/dashboard/leads'
import { Route as DashboardNotificationsRouteImport } from './routes/dashboard/notifications'
import { Route as DashboardSettingsRouteImport } from './routes/dashboard/settings'
import { Route as OnboardingArtistProfileRouteImport } from './routes/onboarding/artist-profile'
import { Route as OnboardingCalendarRouteImport } from './routes/onboarding/calendar'
import { Route as OnboardingHoursRouteImport } from './routes/onboarding/hours'
import { Route as OnboardingProfileRouteImport } from './routes/onboarding/profile'
import { Route as OnboardingTeamRouteImport } from './routes/onboarding/team'
import { Route as OnboardingWhatsappRouteImport } from './routes/onboarding/whatsapp'
import { Route as ApiInternalAppointmentSyncRouteImport } from './routes/api/internal.appointment-sync'
import { Route as ApiGoogleCalendarOauthCallbackRouteImport } from './routes/api/google-calendar.oauth.callback'
import { Route as ApiSettingsBackupsKeyDownloadRouteImport } from './routes/api/settings.backups.$key.download'
import { Route as ApiStaffStaffIdGoogleCalendarConnectRouteImport } from './routes/api/staff.$staffId.google-calendar.connect'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRouteRoute = AuthRouteRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRouteRoute = DashboardRouteRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRouteRoute = OnboardingRouteRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPingRoute = ApiPingRouteImport.update({
  id: '/api/ping',
  path: '/api/ping',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiWhatsappWebhookRoute = ApiWhatsappWebhookRouteImport.update({
  id: '/api/whatsapp-webhook',
  path: '/api/whatsapp-webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthSetupRoute = AuthSetupRouteImport.update({
  id: '/setup',
  path: '/setup',
  getParentRoute: () => AuthRouteRoute,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardCalendarRoute = DashboardCalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardConversationsRoute = DashboardConversationsRouteImport.update({
  id: '/conversations',
  path: '/conversations',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardCustomersRoute = DashboardCustomersRouteImport.update({
  id: '/customers',
  path: '/customers',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardLeadsRoute = DashboardLeadsRouteImport.update({
  id: '/leads',
  path: '/leads',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardNotificationsRoute = DashboardNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardSettingsRoute = DashboardSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const OnboardingArtistProfileRoute = OnboardingArtistProfileRouteImport.update({
  id: '/artist-profile',
  path: '/artist-profile',
  getParentRoute: () => OnboardingRouteRoute,
} as any)
const OnboardingCalendarRoute = OnboardingCalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => OnboardingRouteRoute,
} as any)
const OnboardingHoursRoute = OnboardingHoursRouteImport.update({
  id: '/hours',
  path: '/hours',
  getParentRoute: () => OnboardingRouteRoute,
} as any)
const OnboardingProfileRoute = OnboardingProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => OnboardingRouteRoute,
} as any)
const OnboardingTeamRoute = OnboardingTeamRouteImport.update({
  id: '/team',
  path: '/team',
  getParentRoute: () => OnboardingRouteRoute,
} as any)
const OnboardingWhatsappRoute = OnboardingWhatsappRouteImport.update({
  id: '/whatsapp',
  path: '/whatsapp',
  getParentRoute: () => OnboardingRouteRoute,
} as any)
const ApiInternalAppointmentSyncRoute =
  ApiInternalAppointmentSyncRouteImport.update({
    id: '/api/internal/appointment-sync',
    path: '/api/internal/appointment-sync',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiGoogleCalendarOauthCallbackRoute =
  ApiGoogleCalendarOauthCallbackRouteImport.update({
    id: '/api/google-calendar/oauth/callback',
    path: '/api/google-calendar/oauth/callback',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiSettingsBackupsKeyDownloadRoute =
  ApiSettingsBackupsKeyDownloadRouteImport.update({
    id: '/api/settings/backups/$key/download',
    path: '/api/settings/backups/$key/download',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiStaffStaffIdGoogleCalendarConnectRoute =
  ApiStaffStaffIdGoogleCalendarConnectRouteImport.update({
    id: '/api/staff/$staffId/google-calendar/connect',
    path: '/api/staff/$staffId/google-calendar/connect',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRouteRouteWithChildren
  '/dashboard': typeof DashboardRouteRouteWithChildren
  '/onboarding': typeof OnboardingRouteRouteWithChildren
  '/api/ping': typeof ApiPingRoute
  '/api/whatsapp-webhook': typeof ApiWhatsappWebhookRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/setup': typeof AuthSetupRoute
  '/dashboard/calendar': typeof DashboardCalendarRoute
  '/dashboard/conversations': typeof DashboardConversationsRoute
  '/dashboard/customers': typeof DashboardCustomersRoute
  '/dashboard/leads': typeof DashboardLeadsRoute
  '/dashboard/notifications': typeof DashboardNotificationsRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/onboarding/artist-profile': typeof OnboardingArtistProfileRoute
  '/onboarding/calendar': typeof OnboardingCalendarRoute
  '/onboarding/hours': typeof OnboardingHoursRoute
  '/onboarding/profile': typeof OnboardingProfileRoute
  '/onboarding/team': typeof OnboardingTeamRoute
  '/onboarding/whatsapp': typeof OnboardingWhatsappRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/api/internal/appointment-sync': typeof ApiInternalAppointmentSyncRoute
  '/api/google-calendar/oauth/callback': typeof ApiGoogleCalendarOauthCallbackRoute
  '/api/settings/backups/$key/download': typeof ApiSettingsBackupsKeyDownloadRoute
  '/api/staff/$staffId/google-calendar/connect': typeof ApiStaffStaffIdGoogleCalendarConnectRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRouteRouteWithChildren
  '/onboarding': typeof OnboardingRouteRouteWithChildren
  '/api/ping': typeof ApiPingRoute
  '/api/whatsapp-webhook': typeof ApiWhatsappWebhookRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/setup': typeof AuthSetupRoute
  '/dashboard/calendar': typeof DashboardCalendarRoute
  '/dashboard/conversations': typeof DashboardConversationsRoute
  '/dashboard/customers': typeof DashboardCustomersRoute
  '/dashboard/leads': typeof DashboardLeadsRoute
  '/dashboard/notifications': typeof DashboardNotificationsRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/onboarding/artist-profile': typeof OnboardingArtistProfileRoute
  '/onboarding/calendar': typeof OnboardingCalendarRoute
  '/onboarding/hours': typeof OnboardingHoursRoute
  '/onboarding/profile': typeof OnboardingProfileRoute
  '/onboarding/team': typeof OnboardingTeamRoute
  '/onboarding/whatsapp': typeof OnboardingWhatsappRoute
  '/dashboard': typeof DashboardIndexRoute
  '/api/internal/appointment-sync': typeof ApiInternalAppointmentSyncRoute
  '/api/google-calendar/oauth/callback': typeof ApiGoogleCalendarOauthCallbackRoute
  '/api/settings/backups/$key/download': typeof ApiSettingsBackupsKeyDownloadRoute
  '/api/staff/$staffId/google-calendar/connect': typeof ApiStaffStaffIdGoogleCalendarConnectRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRouteRouteWithChildren
  '/dashboard': typeof DashboardRouteRouteWithChildren
  '/onboarding': typeof OnboardingRouteRouteWithChildren
  '/api/ping': typeof ApiPingRoute
  '/api/whatsapp-webhook': typeof ApiWhatsappWebhookRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/setup': typeof AuthSetupRoute
  '/dashboard/calendar': typeof DashboardCalendarRoute
  '/dashboard/conversations': typeof DashboardConversationsRoute
  '/dashboard/customers': typeof DashboardCustomersRoute
  '/dashboard/leads': typeof DashboardLeadsRoute
  '/dashboard/notifications': typeof DashboardNotificationsRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/onboarding/artist-profile': typeof OnboardingArtistProfileRoute
  '/onboarding/calendar': typeof OnboardingCalendarRoute
  '/onboarding/hours': typeof OnboardingHoursRoute
  '/onboarding/profile': typeof OnboardingProfileRoute
  '/onboarding/team': typeof OnboardingTeamRoute
  '/onboarding/whatsapp': typeof OnboardingWhatsappRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/api/internal/appointment-sync': typeof ApiInternalAppointmentSyncRoute
  '/api/google-calendar/oauth/callback': typeof ApiGoogleCalendarOauthCallbackRoute
  '/api/settings/backups/$key/download': typeof ApiSettingsBackupsKeyDownloadRoute
  '/api/staff/$staffId/google-calendar/connect': typeof ApiStaffStaffIdGoogleCalendarConnectRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/dashboard'
    | '/onboarding'
    | '/api/ping'
    | '/api/whatsapp-webhook'
    | '/auth/login'
    | '/auth/setup'
    | '/dashboard/calendar'
    | '/dashboard/conversations'
    | '/dashboard/customers'
    | '/dashboard/leads'
    | '/dashboard/notifications'
    | '/dashboard/settings'
    | '/onboarding/artist-profile'
    | '/onboarding/calendar'
    | '/onboarding/hours'
    | '/onboarding/profile'
    | '/onboarding/team'
    | '/onboarding/whatsapp'
    | '/dashboard/'
    | '/api/internal/appointment-sync'
    | '/api/google-calendar/oauth/callback'
    | '/api/settings/backups/$key/download'
    | '/api/staff/$staffId/google-calendar/connect'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/onboarding'
    | '/api/ping'
    | '/api/whatsapp-webhook'
    | '/auth/login'
    | '/auth/setup'
    | '/dashboard/calendar'
    | '/dashboard/conversations'
    | '/dashboard/customers'
    | '/dashboard/leads'
    | '/dashboard/notifications'
    | '/dashboard/settings'
    | '/onboarding/artist-profile'
    | '/onboarding/calendar'
    | '/onboarding/hours'
    | '/onboarding/profile'
    | '/onboarding/team'
    | '/onboarding/whatsapp'
    | '/dashboard'
    | '/api/internal/appointment-sync'
    | '/api/google-calendar/oauth/callback'
    | '/api/settings/backups/$key/download'
    | '/api/staff/$staffId/google-calendar/connect'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/dashboard'
    | '/onboarding'
    | '/api/ping'
    | '/api/whatsapp-webhook'
    | '/auth/login'
    | '/auth/setup'
    | '/dashboard/calendar'
    | '/dashboard/conversations'
    | '/dashboard/customers'
    | '/dashboard/leads'
    | '/dashboard/notifications'
    | '/dashboard/settings'
    | '/onboarding/artist-profile'
    | '/onboarding/calendar'
    | '/onboarding/hours'
    | '/onboarding/profile'
    | '/onboarding/team'
    | '/onboarding/whatsapp'
    | '/dashboard/'
    | '/api/internal/appointment-sync'
    | '/api/google-calendar/oauth/callback'
    | '/api/settings/backups/$key/download'
    | '/api/staff/$staffId/google-calendar/connect'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRouteRoute: typeof AuthRouteRouteWithChildren
  DashboardRouteRoute: typeof DashboardRouteRouteWithChildren
  OnboardingRouteRoute: typeof OnboardingRouteRouteWithChildren
  ApiPingRoute: typeof ApiPingRoute
  ApiWhatsappWebhookRoute: typeof ApiWhatsappWebhookRoute
  ApiInternalAppointmentSyncRoute: typeof ApiInternalAppointmentSyncRoute
  ApiGoogleCalendarOauthCallbackRoute: typeof ApiGoogleCalendarOauthCallbackRoute
  ApiSettingsBackupsKeyDownloadRoute: typeof ApiSettingsBackupsKeyDownloadRoute
  ApiStaffStaffIdGoogleCalendarConnectRoute: typeof ApiStaffStaffIdGoogleCalendarConnectRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/ping': {
      id: '/api/ping'
      path: '/api/ping'
      fullPath: '/api/ping'
      preLoaderRoute: typeof ApiPingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/whatsapp-webhook': {
      id: '/api/whatsapp-webhook'
      path: '/api/whatsapp-webhook'
      fullPath: '/api/whatsapp-webhook'
      preLoaderRoute: typeof ApiWhatsappWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/login': {
      id: '/auth/login'
      path: '/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/auth/setup': {
      id: '/auth/setup'
      path: '/setup'
      fullPath: '/auth/setup'
      preLoaderRoute: typeof AuthSetupRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/calendar': {
      id: '/dashboard/calendar'
      path: '/calendar'
      fullPath: '/dashboard/calendar'
      preLoaderRoute: typeof DashboardCalendarRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/conversations': {
      id: '/dashboard/conversations'
      path: '/conversations'
      fullPath: '/dashboard/conversations'
      preLoaderRoute: typeof DashboardConversationsRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/customers': {
      id: '/dashboard/customers'
      path: '/customers'
      fullPath: '/dashboard/customers'
      preLoaderRoute: typeof DashboardCustomersRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/leads': {
      id: '/dashboard/leads'
      path: '/leads'
      fullPath: '/dashboard/leads'
      preLoaderRoute: typeof DashboardLeadsRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/notifications': {
      id: '/dashboard/notifications'
      path: '/notifications'
      fullPath: '/dashboard/notifications'
      preLoaderRoute: typeof DashboardNotificationsRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/settings': {
      id: '/dashboard/settings'
      path: '/settings'
      fullPath: '/dashboard/settings'
      preLoaderRoute: typeof DashboardSettingsRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/onboarding/artist-profile': {
      id: '/onboarding/artist-profile'
      path: '/artist-profile'
      fullPath: '/onboarding/artist-profile'
      preLoaderRoute: typeof OnboardingArtistProfileRouteImport
      parentRoute: typeof OnboardingRouteRoute
    }
    '/onboarding/calendar': {
      id: '/onboarding/calendar'
      path: '/calendar'
      fullPath: '/onboarding/calendar'
      preLoaderRoute: typeof OnboardingCalendarRouteImport
      parentRoute: typeof OnboardingRouteRoute
    }
    '/onboarding/hours': {
      id: '/onboarding/hours'
      path: '/hours'
      fullPath: '/onboarding/hours'
      preLoaderRoute: typeof OnboardingHoursRouteImport
      parentRoute: typeof OnboardingRouteRoute
    }
    '/onboarding/profile': {
      id: '/onboarding/profile'
      path: '/profile'
      fullPath: '/onboarding/profile'
      preLoaderRoute: typeof OnboardingProfileRouteImport
      parentRoute: typeof OnboardingRouteRoute
    }
    '/onboarding/team': {
      id: '/onboarding/team'
      path: '/team'
      fullPath: '/onboarding/team'
      preLoaderRoute: typeof OnboardingTeamRouteImport
      parentRoute: typeof OnboardingRouteRoute
    }
    '/onboarding/whatsapp': {
      id: '/onboarding/whatsapp'
      path: '/whatsapp'
      fullPath: '/onboarding/whatsapp'
      preLoaderRoute: typeof OnboardingWhatsappRouteImport
      parentRoute: typeof OnboardingRouteRoute
    }
    '/api/internal/appointment-sync': {
      id: '/api/internal/appointment-sync'
      path: '/api/internal/appointment-sync'
      fullPath: '/api/internal/appointment-sync'
      preLoaderRoute: typeof ApiInternalAppointmentSyncRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/google-calendar/oauth/callback': {
      id: '/api/google-calendar/oauth/callback'
      path: '/api/google-calendar/oauth/callback'
      fullPath: '/api/google-calendar/oauth/callback'
      preLoaderRoute: typeof ApiGoogleCalendarOauthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/settings/backups/$key/download': {
      id: '/api/settings/backups/$key/download'
      path: '/api/settings/backups/$key/download'
      fullPath: '/api/settings/backups/$key/download'
      preLoaderRoute: typeof ApiSettingsBackupsKeyDownloadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/staff/$staffId/google-calendar/connect': {
      id: '/api/staff/$staffId/google-calendar/connect'
      path: '/api/staff/$staffId/google-calendar/connect'
      fullPath: '/api/staff/$staffId/google-calendar/connect'
      preLoaderRoute: typeof ApiStaffStaffIdGoogleCalendarConnectRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthRouteRouteChildren {
  AuthLoginRoute: typeof AuthLoginRoute
  AuthSetupRoute: typeof AuthSetupRoute
}

const AuthRouteRouteChildren: AuthRouteRouteChildren = {
  AuthLoginRoute: AuthLoginRoute,
  AuthSetupRoute: AuthSetupRoute,
}

const AuthRouteRouteWithChildren = AuthRouteRoute._addFileChildren(
  AuthRouteRouteChildren,
)

interface DashboardRouteRouteChildren {
  DashboardCalendarRoute: typeof DashboardCalendarRoute
  DashboardConversationsRoute: typeof DashboardConversationsRoute
  DashboardCustomersRoute: typeof DashboardCustomersRoute
  DashboardLeadsRoute: typeof DashboardLeadsRoute
  DashboardNotificationsRoute: typeof DashboardNotificationsRoute
  DashboardSettingsRoute: typeof DashboardSettingsRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
}

const DashboardRouteRouteChildren: DashboardRouteRouteChildren = {
  DashboardCalendarRoute: DashboardCalendarRoute,
  DashboardConversationsRoute: DashboardConversationsRoute,
  DashboardCustomersRoute: DashboardCustomersRoute,
  DashboardLeadsRoute: DashboardLeadsRoute,
  DashboardNotificationsRoute: DashboardNotificationsRoute,
  DashboardSettingsRoute: DashboardSettingsRoute,
  DashboardIndexRoute: DashboardIndexRoute,
}

const DashboardRouteRouteWithChildren = DashboardRouteRoute._addFileChildren(
  DashboardRouteRouteChildren,
)

interface OnboardingRouteRouteChildren {
  OnboardingArtistProfileRoute: typeof OnboardingArtistProfileRoute
  OnboardingCalendarRoute: typeof OnboardingCalendarRoute
  OnboardingHoursRoute: typeof OnboardingHoursRoute
  OnboardingProfileRoute: typeof OnboardingProfileRoute
  OnboardingTeamRoute: typeof OnboardingTeamRoute
  OnboardingWhatsappRoute: typeof OnboardingWhatsappRoute
}

const OnboardingRouteRouteChildren: OnboardingRouteRouteChildren = {
  OnboardingArtistProfileRoute: OnboardingArtistProfileRoute,
  OnboardingCalendarRoute: OnboardingCalendarRoute,
  OnboardingHoursRoute: OnboardingHoursRoute,
  OnboardingProfileRoute: OnboardingProfileRoute,
  OnboardingTeamRoute: OnboardingTeamRoute,
  OnboardingWhatsappRoute: OnboardingWhatsappRoute,
}

const OnboardingRouteRouteWithChildren = OnboardingRouteRoute._addFileChildren(
  OnboardingRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRouteRoute: AuthRouteRouteWithChildren,
  DashboardRouteRoute: DashboardRouteRouteWithChildren,
  OnboardingRouteRoute: OnboardingRouteRouteWithChildren,
  ApiPingRoute: ApiPingRoute,
  ApiWhatsappWebhookRoute: ApiWhatsappWebhookRoute,
  ApiInternalAppointmentSyncRoute: ApiInternalAppointmentSyncRoute,
  ApiGoogleCalendarOauthCallbackRoute: ApiGoogleCalendarOauthCallbackRoute,
  ApiSettingsBackupsKeyDownloadRoute: ApiSettingsBackupsKeyDownloadRoute,
  ApiStaffStaffIdGoogleCalendarConnectRoute:
    ApiStaffStaffIdGoogleCalendarConnectRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
