/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthRouteRouteImport } from './routes/auth/route'
import { Route as DashboardRouteRouteImport } from './routes/dashboard/route'
import { Route as InviteRouteImport } from './routes/invite'
import { Route as OnboardingRouteRouteImport } from './routes/onboarding/route'
import { Route as ApiPingRouteImport } from './routes/api/ping'
import { Route as ApiWhatsappWebhookRouteImport } from './routes/api/whatsapp-webhook'
import { Route as AuthForgotPasswordRouteImport } from './routes/auth/forgot-password'
import { Route as AuthLoginRouteImport } from './routes/auth/login'
import { Route as AuthResetPasswordRouteImport } from './routes/auth/reset-password'
import { Route as AuthSetupRouteImport } from './routes/auth/setup'
import { Route as DashboardIndexRouteImport } from './routes/dashboard/index'
import { Route as DashboardAnalyticsRouteImport } from './routes/dashboard/analytics'
import { Route as DashboardCalendarRouteImport } from './routes/dashboard/calendar'
import { Route as DashboardConversationsRouteImport } from './routes/dashboard/conversations'
import { Route as DashboardCustomersRouteImport } from './routes/dashboard/customers'
import { Route as DashboardLeadsRouteImport } from './routes/dashboard/leads'
import { Route as DashboardNotificationsRouteImport } from './routes/dashboard/notifications'
import { Route as DashboardSettingsRouteRouteImport } from './routes/dashboard/settings/route'
import { Route as DashboardSetupRouteImport } from './routes/dashboard/setup'
import { Route as OnboardingIndexRouteImport } from './routes/onboarding/index'
import { Route as OnboardingDoneRouteImport } from './routes/onboarding/done'
import { Route as OnboardingHoursRouteImport } from './routes/onboarding/hours'
import { Route as OnboardingProfileLinksRouteImport } from './routes/onboarding/profile-links'
import { Route as OnboardingStudioRouteImport } from './routes/onboarding/studio'
import { Route as ApiHealthDeclarationWebhookRouteImport } from './routes/api/health-declaration.webhook'
import { Route as ApiInternalAppointmentFreedRouteImport } from './routes/api/internal.appointment-freed'
import { Route as ApiInternalAppointmentSyncRouteImport } from './routes/api/internal.appointment-sync'
import { Route as ApiInternalLifecycleTickRouteImport } from './routes/api/internal.lifecycle-tick'
import { Route as DashboardSettingsIndexRouteImport } from './routes/dashboard/settings/index'
import { Route as DashboardSettingsAiRouteImport } from './routes/dashboard/settings/ai'
import { Route as DashboardSettingsGeneralRouteImport } from './routes/dashboard/settings/general'
import { Route as DashboardSettingsPolicyRouteImport } from './routes/dashboard/settings/policy'
import { Route as DashboardSettingsSystemRouteImport } from './routes/dashboard/settings/system'
import { Route as DashboardSettingsTeamRouteImport } from './routes/dashboard/settings/team'
import { Route as ApiGoogleCalendarOauthCallbackRouteImport } from './routes/api/google-calendar.oauth.callback'
import { Route as ApiSettingsBackupsUploadRouteImport } from './routes/api/settings.backups.upload'
import { Route as ApiSettingsBackupsKeyDownloadRouteImport } from './routes/api/settings.backups.$key.download'
import { Route as ApiStaffStaffIdGoogleCalendarConnectRouteImport } from './routes/api/staff.$staffId.google-calendar.connect'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRouteRoute = AuthRouteRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRouteRoute = DashboardRouteRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const InviteRoute = InviteRouteImport.update({
  id: '/invite',
  path: '/invite',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRouteRoute = OnboardingRouteRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPingRoute = ApiPingRouteImport.update({
  id: '/api/ping',
  path: '/api/ping',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiWhatsappWebhookRoute = ApiWhatsappWebhookRouteImport.update({
  id: '/api/whatsapp-webhook',
  path: '/api/whatsapp-webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthForgotPasswordRoute = AuthForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthResetPasswordRoute = AuthResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthSetupRoute = AuthSetupRouteImport.update({
  id: '/setup',
  path: '/setup',
  getParentRoute: () => AuthRouteRoute,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardAnalyticsRoute = DashboardAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardCalendarRoute = DashboardCalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardConversationsRoute = DashboardConversationsRouteImport.update({
  id: '/conversations',
  path: '/conversations',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardCustomersRoute = DashboardCustomersRouteImport.update({
  id: '/customers',
  path: '/customers',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardLeadsRoute = DashboardLeadsRouteImport.update({
  id: '/leads',
  path: '/leads',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardNotificationsRoute = DashboardNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardSettingsRouteRoute = DashboardSettingsRouteRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardSetupRoute = DashboardSetupRouteImport.update({
  id: '/setup',
  path: '/setup',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const OnboardingIndexRoute = OnboardingIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => OnboardingRouteRoute,
} as any)
const OnboardingDoneRoute = OnboardingDoneRouteImport.update({
  id: '/done',
  path: '/done',
  getParentRoute: () => OnboardingRouteRoute,
} as any)
const OnboardingHoursRoute = OnboardingHoursRouteImport.update({
  id: '/hours',
  path: '/hours',
  getParentRoute: () => OnboardingRouteRoute,
} as any)
const OnboardingProfileLinksRoute = OnboardingProfileLinksRouteImport.update({
  id: '/profile-links',
  path: '/profile-links',
  getParentRoute: () => OnboardingRouteRoute,
} as any)
const OnboardingStudioRoute = OnboardingStudioRouteImport.update({
  id: '/studio',
  path: '/studio',
  getParentRoute: () => OnboardingRouteRoute,
} as any)
const ApiHealthDeclarationWebhookRoute =
  ApiHealthDeclarationWebhookRouteImport.update({
    id: '/api/health-declaration/webhook',
    path: '/api/health-declaration/webhook',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiInternalAppointmentFreedRoute =
  ApiInternalAppointmentFreedRouteImport.update({
    id: '/api/internal/appointment-freed',
    path: '/api/internal/appointment-freed',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiInternalAppointmentSyncRoute =
  ApiInternalAppointmentSyncRouteImport.update({
    id: '/api/internal/appointment-sync',
    path: '/api/internal/appointment-sync',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiInternalLifecycleTickRoute =
  ApiInternalLifecycleTickRouteImport.update({
    id: '/api/internal/lifecycle-tick',
    path: '/api/internal/lifecycle-tick',
    getParentRoute: () => rootRouteImport,
  } as any)
const DashboardSettingsIndexRoute = DashboardSettingsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardSettingsRouteRoute,
} as any)
const DashboardSettingsAiRoute = DashboardSettingsAiRouteImport.update({
  id: '/ai',
  path: '/ai',
  getParentRoute: () => DashboardSettingsRouteRoute,
} as any)
const DashboardSettingsGeneralRoute =
  DashboardSettingsGeneralRouteImport.update({
    id: '/general',
    path: '/general',
    getParentRoute: () => DashboardSettingsRouteRoute,
  } as any)
const DashboardSettingsPolicyRoute = DashboardSettingsPolicyRouteImport.update({
  id: '/policy',
  path: '/policy',
  getParentRoute: () => DashboardSettingsRouteRoute,
} as any)
const DashboardSettingsSystemRoute = DashboardSettingsSystemRouteImport.update({
  id: '/system',
  path: '/system',
  getParentRoute: () => DashboardSettingsRouteRoute,
} as any)
const DashboardSettingsTeamRoute = DashboardSettingsTeamRouteImport.update({
  id: '/team',
  path: '/team',
  getParentRoute: () => DashboardSettingsRouteRoute,
} as any)
const ApiGoogleCalendarOauthCallbackRoute =
  ApiGoogleCalendarOauthCallbackRouteImport.update({
    id: '/api/google-calendar/oauth/callback',
    path: '/api/google-calendar/oauth/callback',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiSettingsBackupsUploadRoute =
  ApiSettingsBackupsUploadRouteImport.update({
    id: '/api/settings/backups/upload',
    path: '/api/settings/backups/upload',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiSettingsBackupsKeyDownloadRoute =
  ApiSettingsBackupsKeyDownloadRouteImport.update({
    id: '/api/settings/backups/$key/download',
    path: '/api/settings/backups/$key/download',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiStaffStaffIdGoogleCalendarConnectRoute =
  ApiStaffStaffIdGoogleCalendarConnectRouteImport.update({
    id: '/api/staff/$staffId/google-calendar/connect',
    path: '/api/staff/$staffId/google-calendar/connect',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRouteRouteWithChildren
  '/dashboard': typeof DashboardRouteRouteWithChildren
  '/onboarding': typeof OnboardingRouteRouteWithChildren
  '/invite': typeof InviteRoute
  '/dashboard/settings': typeof DashboardSettingsRouteRouteWithChildren
  '/api/ping': typeof ApiPingRoute
  '/api/whatsapp-webhook': typeof ApiWhatsappWebhookRoute
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/reset-password': typeof AuthResetPasswordRoute
  '/auth/setup': typeof AuthSetupRoute
  '/dashboard/analytics': typeof DashboardAnalyticsRoute
  '/dashboard/calendar': typeof DashboardCalendarRoute
  '/dashboard/conversations': typeof DashboardConversationsRoute
  '/dashboard/customers': typeof DashboardCustomersRoute
  '/dashboard/leads': typeof DashboardLeadsRoute
  '/dashboard/notifications': typeof DashboardNotificationsRoute
  '/dashboard/setup': typeof DashboardSetupRoute
  '/onboarding/done': typeof OnboardingDoneRoute
  '/onboarding/hours': typeof OnboardingHoursRoute
  '/onboarding/profile-links': typeof OnboardingProfileLinksRoute
  '/onboarding/studio': typeof OnboardingStudioRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/onboarding/': typeof OnboardingIndexRoute
  '/api/health-declaration/webhook': typeof ApiHealthDeclarationWebhookRoute
  '/api/internal/appointment-freed': typeof ApiInternalAppointmentFreedRoute
  '/api/internal/appointment-sync': typeof ApiInternalAppointmentSyncRoute
  '/api/internal/lifecycle-tick': typeof ApiInternalLifecycleTickRoute
  '/dashboard/settings/ai': typeof DashboardSettingsAiRoute
  '/dashboard/settings/general': typeof DashboardSettingsGeneralRoute
  '/dashboard/settings/policy': typeof DashboardSettingsPolicyRoute
  '/dashboard/settings/system': typeof DashboardSettingsSystemRoute
  '/dashboard/settings/team': typeof DashboardSettingsTeamRoute
  '/dashboard/settings/': typeof DashboardSettingsIndexRoute
  '/api/google-calendar/oauth/callback': typeof ApiGoogleCalendarOauthCallbackRoute
  '/api/settings/backups/upload': typeof ApiSettingsBackupsUploadRoute
  '/api/settings/backups/$key/download': typeof ApiSettingsBackupsKeyDownloadRoute
  '/api/staff/$staffId/google-calendar/connect': typeof ApiStaffStaffIdGoogleCalendarConnectRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRouteRouteWithChildren
  '/invite': typeof InviteRoute
  '/api/ping': typeof ApiPingRoute
  '/api/whatsapp-webhook': typeof ApiWhatsappWebhookRoute
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/reset-password': typeof AuthResetPasswordRoute
  '/auth/setup': typeof AuthSetupRoute
  '/dashboard/analytics': typeof DashboardAnalyticsRoute
  '/dashboard/calendar': typeof DashboardCalendarRoute
  '/dashboard/conversations': typeof DashboardConversationsRoute
  '/dashboard/customers': typeof DashboardCustomersRoute
  '/dashboard/leads': typeof DashboardLeadsRoute
  '/dashboard/notifications': typeof DashboardNotificationsRoute
  '/dashboard/setup': typeof DashboardSetupRoute
  '/onboarding/done': typeof OnboardingDoneRoute
  '/onboarding/hours': typeof OnboardingHoursRoute
  '/onboarding/profile-links': typeof OnboardingProfileLinksRoute
  '/onboarding/studio': typeof OnboardingStudioRoute
  '/dashboard': typeof DashboardIndexRoute
  '/onboarding': typeof OnboardingIndexRoute
  '/api/health-declaration/webhook': typeof ApiHealthDeclarationWebhookRoute
  '/api/internal/appointment-freed': typeof ApiInternalAppointmentFreedRoute
  '/api/internal/appointment-sync': typeof ApiInternalAppointmentSyncRoute
  '/api/internal/lifecycle-tick': typeof ApiInternalLifecycleTickRoute
  '/dashboard/settings/ai': typeof DashboardSettingsAiRoute
  '/dashboard/settings/general': typeof DashboardSettingsGeneralRoute
  '/dashboard/settings/policy': typeof DashboardSettingsPolicyRoute
  '/dashboard/settings/system': typeof DashboardSettingsSystemRoute
  '/dashboard/settings/team': typeof DashboardSettingsTeamRoute
  '/dashboard/settings': typeof DashboardSettingsIndexRoute
  '/api/google-calendar/oauth/callback': typeof ApiGoogleCalendarOauthCallbackRoute
  '/api/settings/backups/upload': typeof ApiSettingsBackupsUploadRoute
  '/api/settings/backups/$key/download': typeof ApiSettingsBackupsKeyDownloadRoute
  '/api/staff/$staffId/google-calendar/connect': typeof ApiStaffStaffIdGoogleCalendarConnectRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRouteRouteWithChildren
  '/dashboard': typeof DashboardRouteRouteWithChildren
  '/onboarding': typeof OnboardingRouteRouteWithChildren
  '/invite': typeof InviteRoute
  '/dashboard/settings': typeof DashboardSettingsRouteRouteWithChildren
  '/api/ping': typeof ApiPingRoute
  '/api/whatsapp-webhook': typeof ApiWhatsappWebhookRoute
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/reset-password': typeof AuthResetPasswordRoute
  '/auth/setup': typeof AuthSetupRoute
  '/dashboard/analytics': typeof DashboardAnalyticsRoute
  '/dashboard/calendar': typeof DashboardCalendarRoute
  '/dashboard/conversations': typeof DashboardConversationsRoute
  '/dashboard/customers': typeof DashboardCustomersRoute
  '/dashboard/leads': typeof DashboardLeadsRoute
  '/dashboard/notifications': typeof DashboardNotificationsRoute
  '/dashboard/setup': typeof DashboardSetupRoute
  '/onboarding/done': typeof OnboardingDoneRoute
  '/onboarding/hours': typeof OnboardingHoursRoute
  '/onboarding/profile-links': typeof OnboardingProfileLinksRoute
  '/onboarding/studio': typeof OnboardingStudioRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/onboarding/': typeof OnboardingIndexRoute
  '/api/health-declaration/webhook': typeof ApiHealthDeclarationWebhookRoute
  '/api/internal/appointment-freed': typeof ApiInternalAppointmentFreedRoute
  '/api/internal/appointment-sync': typeof ApiInternalAppointmentSyncRoute
  '/api/internal/lifecycle-tick': typeof ApiInternalLifecycleTickRoute
  '/dashboard/settings/ai': typeof DashboardSettingsAiRoute
  '/dashboard/settings/general': typeof DashboardSettingsGeneralRoute
  '/dashboard/settings/policy': typeof DashboardSettingsPolicyRoute
  '/dashboard/settings/system': typeof DashboardSettingsSystemRoute
  '/dashboard/settings/team': typeof DashboardSettingsTeamRoute
  '/dashboard/settings/': typeof DashboardSettingsIndexRoute
  '/api/google-calendar/oauth/callback': typeof ApiGoogleCalendarOauthCallbackRoute
  '/api/settings/backups/upload': typeof ApiSettingsBackupsUploadRoute
  '/api/settings/backups/$key/download': typeof ApiSettingsBackupsKeyDownloadRoute
  '/api/staff/$staffId/google-calendar/connect': typeof ApiStaffStaffIdGoogleCalendarConnectRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/dashboard'
    | '/onboarding'
    | '/invite'
    | '/dashboard/settings'
    | '/api/ping'
    | '/api/whatsapp-webhook'
    | '/auth/forgot-password'
    | '/auth/login'
    | '/auth/reset-password'
    | '/auth/setup'
    | '/dashboard/analytics'
    | '/dashboard/calendar'
    | '/dashboard/conversations'
    | '/dashboard/customers'
    | '/dashboard/leads'
    | '/dashboard/notifications'
    | '/dashboard/setup'
    | '/onboarding/done'
    | '/onboarding/hours'
    | '/onboarding/profile-links'
    | '/onboarding/studio'
    | '/dashboard/'
    | '/onboarding/'
    | '/api/health-declaration/webhook'
    | '/api/internal/appointment-freed'
    | '/api/internal/appointment-sync'
    | '/api/internal/lifecycle-tick'
    | '/dashboard/settings/ai'
    | '/dashboard/settings/general'
    | '/dashboard/settings/policy'
    | '/dashboard/settings/system'
    | '/dashboard/settings/team'
    | '/dashboard/settings/'
    | '/api/google-calendar/oauth/callback'
    | '/api/settings/backups/upload'
    | '/api/settings/backups/$key/download'
    | '/api/staff/$staffId/google-calendar/connect'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/invite'
    | '/api/ping'
    | '/api/whatsapp-webhook'
    | '/auth/forgot-password'
    | '/auth/login'
    | '/auth/reset-password'
    | '/auth/setup'
    | '/dashboard/analytics'
    | '/dashboard/calendar'
    | '/dashboard/conversations'
    | '/dashboard/customers'
    | '/dashboard/leads'
    | '/dashboard/notifications'
    | '/dashboard/setup'
    | '/onboarding/done'
    | '/onboarding/hours'
    | '/onboarding/profile-links'
    | '/onboarding/studio'
    | '/dashboard'
    | '/onboarding'
    | '/api/health-declaration/webhook'
    | '/api/internal/appointment-freed'
    | '/api/internal/appointment-sync'
    | '/api/internal/lifecycle-tick'
    | '/dashboard/settings/ai'
    | '/dashboard/settings/general'
    | '/dashboard/settings/policy'
    | '/dashboard/settings/system'
    | '/dashboard/settings/team'
    | '/dashboard/settings'
    | '/api/google-calendar/oauth/callback'
    | '/api/settings/backups/upload'
    | '/api/settings/backups/$key/download'
    | '/api/staff/$staffId/google-calendar/connect'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/dashboard'
    | '/onboarding'
    | '/invite'
    | '/dashboard/settings'
    | '/api/ping'
    | '/api/whatsapp-webhook'
    | '/auth/forgot-password'
    | '/auth/login'
    | '/auth/reset-password'
    | '/auth/setup'
    | '/dashboard/analytics'
    | '/dashboard/calendar'
    | '/dashboard/conversations'
    | '/dashboard/customers'
    | '/dashboard/leads'
    | '/dashboard/notifications'
    | '/dashboard/setup'
    | '/onboarding/done'
    | '/onboarding/hours'
    | '/onboarding/profile-links'
    | '/onboarding/studio'
    | '/dashboard/'
    | '/onboarding/'
    | '/api/health-declaration/webhook'
    | '/api/internal/appointment-freed'
    | '/api/internal/appointment-sync'
    | '/api/internal/lifecycle-tick'
    | '/dashboard/settings/ai'
    | '/dashboard/settings/general'
    | '/dashboard/settings/policy'
    | '/dashboard/settings/system'
    | '/dashboard/settings/team'
    | '/dashboard/settings/'
    | '/api/google-calendar/oauth/callback'
    | '/api/settings/backups/upload'
    | '/api/settings/backups/$key/download'
    | '/api/staff/$staffId/google-calendar/connect'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRouteRoute: typeof AuthRouteRouteWithChildren
  DashboardRouteRoute: typeof DashboardRouteRouteWithChildren
  OnboardingRouteRoute: typeof OnboardingRouteRouteWithChildren
  InviteRoute: typeof InviteRoute
  ApiPingRoute: typeof ApiPingRoute
  ApiWhatsappWebhookRoute: typeof ApiWhatsappWebhookRoute
  ApiHealthDeclarationWebhookRoute: typeof ApiHealthDeclarationWebhookRoute
  ApiInternalAppointmentFreedRoute: typeof ApiInternalAppointmentFreedRoute
  ApiInternalAppointmentSyncRoute: typeof ApiInternalAppointmentSyncRoute
  ApiInternalLifecycleTickRoute: typeof ApiInternalLifecycleTickRoute
  ApiGoogleCalendarOauthCallbackRoute: typeof ApiGoogleCalendarOauthCallbackRoute
  ApiSettingsBackupsUploadRoute: typeof ApiSettingsBackupsUploadRoute
  ApiSettingsBackupsKeyDownloadRoute: typeof ApiSettingsBackupsKeyDownloadRoute
  ApiStaffStaffIdGoogleCalendarConnectRoute: typeof ApiStaffStaffIdGoogleCalendarConnectRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/invite': {
      id: '/invite'
      path: '/invite'
      fullPath: '/invite'
      preLoaderRoute: typeof InviteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/ping': {
      id: '/api/ping'
      path: '/api/ping'
      fullPath: '/api/ping'
      preLoaderRoute: typeof ApiPingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/whatsapp-webhook': {
      id: '/api/whatsapp-webhook'
      path: '/api/whatsapp-webhook'
      fullPath: '/api/whatsapp-webhook'
      preLoaderRoute: typeof ApiWhatsappWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/forgot-password': {
      id: '/auth/forgot-password'
      path: '/forgot-password'
      fullPath: '/auth/forgot-password'
      preLoaderRoute: typeof AuthForgotPasswordRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/auth/login': {
      id: '/auth/login'
      path: '/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/auth/reset-password': {
      id: '/auth/reset-password'
      path: '/reset-password'
      fullPath: '/auth/reset-password'
      preLoaderRoute: typeof AuthResetPasswordRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/auth/setup': {
      id: '/auth/setup'
      path: '/setup'
      fullPath: '/auth/setup'
      preLoaderRoute: typeof AuthSetupRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/analytics': {
      id: '/dashboard/analytics'
      path: '/analytics'
      fullPath: '/dashboard/analytics'
      preLoaderRoute: typeof DashboardAnalyticsRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/calendar': {
      id: '/dashboard/calendar'
      path: '/calendar'
      fullPath: '/dashboard/calendar'
      preLoaderRoute: typeof DashboardCalendarRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/conversations': {
      id: '/dashboard/conversations'
      path: '/conversations'
      fullPath: '/dashboard/conversations'
      preLoaderRoute: typeof DashboardConversationsRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/customers': {
      id: '/dashboard/customers'
      path: '/customers'
      fullPath: '/dashboard/customers'
      preLoaderRoute: typeof DashboardCustomersRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/leads': {
      id: '/dashboard/leads'
      path: '/leads'
      fullPath: '/dashboard/leads'
      preLoaderRoute: typeof DashboardLeadsRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/notifications': {
      id: '/dashboard/notifications'
      path: '/notifications'
      fullPath: '/dashboard/notifications'
      preLoaderRoute: typeof DashboardNotificationsRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/settings': {
      id: '/dashboard/settings'
      path: '/settings'
      fullPath: '/dashboard/settings'
      preLoaderRoute: typeof DashboardSettingsRouteRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/setup': {
      id: '/dashboard/setup'
      path: '/setup'
      fullPath: '/dashboard/setup'
      preLoaderRoute: typeof DashboardSetupRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/onboarding/': {
      id: '/onboarding/'
      path: '/'
      fullPath: '/onboarding/'
      preLoaderRoute: typeof OnboardingIndexRouteImport
      parentRoute: typeof OnboardingRouteRoute
    }
    '/onboarding/done': {
      id: '/onboarding/done'
      path: '/done'
      fullPath: '/onboarding/done'
      preLoaderRoute: typeof OnboardingDoneRouteImport
      parentRoute: typeof OnboardingRouteRoute
    }
    '/onboarding/hours': {
      id: '/onboarding/hours'
      path: '/hours'
      fullPath: '/onboarding/hours'
      preLoaderRoute: typeof OnboardingHoursRouteImport
      parentRoute: typeof OnboardingRouteRoute
    }
    '/onboarding/profile-links': {
      id: '/onboarding/profile-links'
      path: '/profile-links'
      fullPath: '/onboarding/profile-links'
      preLoaderRoute: typeof OnboardingProfileLinksRouteImport
      parentRoute: typeof OnboardingRouteRoute
    }
    '/onboarding/studio': {
      id: '/onboarding/studio'
      path: '/studio'
      fullPath: '/onboarding/studio'
      preLoaderRoute: typeof OnboardingStudioRouteImport
      parentRoute: typeof OnboardingRouteRoute
    }
    '/api/health-declaration/webhook': {
      id: '/api/health-declaration/webhook'
      path: '/api/health-declaration/webhook'
      fullPath: '/api/health-declaration/webhook'
      preLoaderRoute: typeof ApiHealthDeclarationWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/internal/appointment-freed': {
      id: '/api/internal/appointment-freed'
      path: '/api/internal/appointment-freed'
      fullPath: '/api/internal/appointment-freed'
      preLoaderRoute: typeof ApiInternalAppointmentFreedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/internal/appointment-sync': {
      id: '/api/internal/appointment-sync'
      path: '/api/internal/appointment-sync'
      fullPath: '/api/internal/appointment-sync'
      preLoaderRoute: typeof ApiInternalAppointmentSyncRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/internal/lifecycle-tick': {
      id: '/api/internal/lifecycle-tick'
      path: '/api/internal/lifecycle-tick'
      fullPath: '/api/internal/lifecycle-tick'
      preLoaderRoute: typeof ApiInternalLifecycleTickRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/settings/': {
      id: '/dashboard/settings/'
      path: '/'
      fullPath: '/dashboard/settings/'
      preLoaderRoute: typeof DashboardSettingsIndexRouteImport
      parentRoute: typeof DashboardSettingsRouteRoute
    }
    '/dashboard/settings/ai': {
      id: '/dashboard/settings/ai'
      path: '/ai'
      fullPath: '/dashboard/settings/ai'
      preLoaderRoute: typeof DashboardSettingsAiRouteImport
      parentRoute: typeof DashboardSettingsRouteRoute
    }
    '/dashboard/settings/general': {
      id: '/dashboard/settings/general'
      path: '/general'
      fullPath: '/dashboard/settings/general'
      preLoaderRoute: typeof DashboardSettingsGeneralRouteImport
      parentRoute: typeof DashboardSettingsRouteRoute
    }
    '/dashboard/settings/policy': {
      id: '/dashboard/settings/policy'
      path: '/policy'
      fullPath: '/dashboard/settings/policy'
      preLoaderRoute: typeof DashboardSettingsPolicyRouteImport
      parentRoute: typeof DashboardSettingsRouteRoute
    }
    '/dashboard/settings/system': {
      id: '/dashboard/settings/system'
      path: '/system'
      fullPath: '/dashboard/settings/system'
      preLoaderRoute: typeof DashboardSettingsSystemRouteImport
      parentRoute: typeof DashboardSettingsRouteRoute
    }
    '/dashboard/settings/team': {
      id: '/dashboard/settings/team'
      path: '/team'
      fullPath: '/dashboard/settings/team'
      preLoaderRoute: typeof DashboardSettingsTeamRouteImport
      parentRoute: typeof DashboardSettingsRouteRoute
    }
    '/api/google-calendar/oauth/callback': {
      id: '/api/google-calendar/oauth/callback'
      path: '/api/google-calendar/oauth/callback'
      fullPath: '/api/google-calendar/oauth/callback'
      preLoaderRoute: typeof ApiGoogleCalendarOauthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/settings/backups/upload': {
      id: '/api/settings/backups/upload'
      path: '/api/settings/backups/upload'
      fullPath: '/api/settings/backups/upload'
      preLoaderRoute: typeof ApiSettingsBackupsUploadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/settings/backups/$key/download': {
      id: '/api/settings/backups/$key/download'
      path: '/api/settings/backups/$key/download'
      fullPath: '/api/settings/backups/$key/download'
      preLoaderRoute: typeof ApiSettingsBackupsKeyDownloadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/staff/$staffId/google-calendar/connect': {
      id: '/api/staff/$staffId/google-calendar/connect'
      path: '/api/staff/$staffId/google-calendar/connect'
      fullPath: '/api/staff/$staffId/google-calendar/connect'
      preLoaderRoute: typeof ApiStaffStaffIdGoogleCalendarConnectRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthRouteRouteChildren {
  AuthForgotPasswordRoute: typeof AuthForgotPasswordRoute
  AuthLoginRoute: typeof AuthLoginRoute
  AuthResetPasswordRoute: typeof AuthResetPasswordRoute
  AuthSetupRoute: typeof AuthSetupRoute
}

const AuthRouteRouteChildren: AuthRouteRouteChildren = {
  AuthForgotPasswordRoute: AuthForgotPasswordRoute,
  AuthLoginRoute: AuthLoginRoute,
  AuthResetPasswordRoute: AuthResetPasswordRoute,
  AuthSetupRoute: AuthSetupRoute,
}

const AuthRouteRouteWithChildren = AuthRouteRoute._addFileChildren(
  AuthRouteRouteChildren,
)

interface DashboardSettingsRouteRouteChildren {
  DashboardSettingsAiRoute: typeof DashboardSettingsAiRoute
  DashboardSettingsGeneralRoute: typeof DashboardSettingsGeneralRoute
  DashboardSettingsPolicyRoute: typeof DashboardSettingsPolicyRoute
  DashboardSettingsSystemRoute: typeof DashboardSettingsSystemRoute
  DashboardSettingsTeamRoute: typeof DashboardSettingsTeamRoute
  DashboardSettingsIndexRoute: typeof DashboardSettingsIndexRoute
}

const DashboardSettingsRouteRouteChildren: DashboardSettingsRouteRouteChildren =
  {
    DashboardSettingsAiRoute: DashboardSettingsAiRoute,
    DashboardSettingsGeneralRoute: DashboardSettingsGeneralRoute,
    DashboardSettingsPolicyRoute: DashboardSettingsPolicyRoute,
    DashboardSettingsSystemRoute: DashboardSettingsSystemRoute,
    DashboardSettingsTeamRoute: DashboardSettingsTeamRoute,
    DashboardSettingsIndexRoute: DashboardSettingsIndexRoute,
  }

const DashboardSettingsRouteRouteWithChildren =
  DashboardSettingsRouteRoute._addFileChildren(
    DashboardSettingsRouteRouteChildren,
  )

interface DashboardRouteRouteChildren {
  DashboardSettingsRouteRoute: typeof DashboardSettingsRouteRouteWithChildren
  DashboardAnalyticsRoute: typeof DashboardAnalyticsRoute
  DashboardCalendarRoute: typeof DashboardCalendarRoute
  DashboardConversationsRoute: typeof DashboardConversationsRoute
  DashboardCustomersRoute: typeof DashboardCustomersRoute
  DashboardLeadsRoute: typeof DashboardLeadsRoute
  DashboardNotificationsRoute: typeof DashboardNotificationsRoute
  DashboardSetupRoute: typeof DashboardSetupRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
}

const DashboardRouteRouteChildren: DashboardRouteRouteChildren = {
  DashboardSettingsRouteRoute: DashboardSettingsRouteRouteWithChildren,
  DashboardAnalyticsRoute: DashboardAnalyticsRoute,
  DashboardCalendarRoute: DashboardCalendarRoute,
  DashboardConversationsRoute: DashboardConversationsRoute,
  DashboardCustomersRoute: DashboardCustomersRoute,
  DashboardLeadsRoute: DashboardLeadsRoute,
  DashboardNotificationsRoute: DashboardNotificationsRoute,
  DashboardSetupRoute: DashboardSetupRoute,
  DashboardIndexRoute: DashboardIndexRoute,
}

const DashboardRouteRouteWithChildren = DashboardRouteRoute._addFileChildren(
  DashboardRouteRouteChildren,
)

interface OnboardingRouteRouteChildren {
  OnboardingDoneRoute: typeof OnboardingDoneRoute
  OnboardingHoursRoute: typeof OnboardingHoursRoute
  OnboardingProfileLinksRoute: typeof OnboardingProfileLinksRoute
  OnboardingStudioRoute: typeof OnboardingStudioRoute
  OnboardingIndexRoute: typeof OnboardingIndexRoute
}

const OnboardingRouteRouteChildren: OnboardingRouteRouteChildren = {
  OnboardingDoneRoute: OnboardingDoneRoute,
  OnboardingHoursRoute: OnboardingHoursRoute,
  OnboardingProfileLinksRoute: OnboardingProfileLinksRoute,
  OnboardingStudioRoute: OnboardingStudioRoute,
  OnboardingIndexRoute: OnboardingIndexRoute,
}

const OnboardingRouteRouteWithChildren = OnboardingRouteRoute._addFileChildren(
  OnboardingRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRouteRoute: AuthRouteRouteWithChildren,
  DashboardRouteRoute: DashboardRouteRouteWithChildren,
  OnboardingRouteRoute: OnboardingRouteRouteWithChildren,
  InviteRoute: InviteRoute,
  ApiPingRoute: ApiPingRoute,
  ApiWhatsappWebhookRoute: ApiWhatsappWebhookRoute,
  ApiHealthDeclarationWebhookRoute: ApiHealthDeclarationWebhookRoute,
  ApiInternalAppointmentFreedRoute: ApiInternalAppointmentFreedRoute,
  ApiInternalAppointmentSyncRoute: ApiInternalAppointmentSyncRoute,
  ApiInternalLifecycleTickRoute: ApiInternalLifecycleTickRoute,
  ApiGoogleCalendarOauthCallbackRoute: ApiGoogleCalendarOauthCallbackRoute,
  ApiSettingsBackupsUploadRoute: ApiSettingsBackupsUploadRoute,
  ApiSettingsBackupsKeyDownloadRoute: ApiSettingsBackupsKeyDownloadRoute,
  ApiStaffStaffIdGoogleCalendarConnectRoute:
    ApiStaffStaffIdGoogleCalendarConnectRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
