/// <reference path="../pb_data/types.d.ts" />

// Modernized for PocketBase v0.39 JS API — the old `$app.dao()`/`txDao.saveRecord(...)` calls
// (removed from PocketBase in v0.23+) were silently erroring on every run, so stale pending
// appointments were never actually being auto-cancelled. See pocketbase/pb_data/types.d.ts
// (auto-generated by the installed binary) for the current API surface.
cronAdd("cleanupPendingAppointments", "0 */2 * * *", () => {
    // Calculate date limit: 48 hours ago
    const limitDate = new Date(Date.now() - 48 * 60 * 60 * 1000);
    // Format to SQLite-compatible YYYY-MM-DD HH:MM:SS format
    const limitStr = limitDate.toISOString().replace('T', ' ').substring(0, 19);

    // Find pending appointments created more than 48 hours ago
    const appointments = $app.findRecordsByFilter(
        "appointments",
        "status = 'pending' && created < {:limit}",
        "-created",
        100,
        0,
        { limit: limitStr }
    );

    for (const appt of appointments) {
        $app.runInTransaction((txApp) => {
            // Cancel the appointment
            appt.set("status", "cancelled");
            txApp.save(appt);

            // Also release the conversation state if it is currently stuck waiting
            const customerId = appt.get("customer");
            try {
                const conv = txApp.findFirstRecordByFilter(
                    "conversations",
                    "customer = {:customerId}",
                    { customerId: customerId }
                );
                const currentState = conv.get("state");
                if (currentState === "AWAIT_PRICE_OFFER" || currentState === "AWAIT_PAYMENT" || currentState === "AWAIT_FINAL_CONFIRMATION") {
                    conv.set("state", "COLLECTING_INFO");
                    txApp.save(conv);
                }
            } catch (e) {
                // Conversation might not exist or state is already different
            }
        });
    }
});
